"""Add is_active to users

Revision ID: d8fcae0c007c
Revises: aa53f263ec78
Create Date: 2026-01-23 16:52:31.206962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8fcae0c007c'
down_revision: Union[str, Sequence[str], None] = 'aa53f263ec78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('payment_reminders')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_vendor_payments_payment_number'), table_name='vendor_payments')
    op.drop_table('vendor_payments')
    op.drop_index(op.f('transaction_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_enquiries_id'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_table('orders')
    op.drop_table('readymade_products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('vendors')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('joined_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vendors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('vendor_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('gstin', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pan', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bank_account', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ifsc_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('file', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('features', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('readymade_products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quality', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('readymade_product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_address', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('cancellation_requested', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_orders_product_id'),
    sa.ForeignKeyConstraint(['readymade_product_id'], ['readymade_products.id'], name='fk_orders_readymade_product_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_orders_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enquiries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_enquiries_id'), 'enquiries', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('day', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_sales_order_id')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('sales_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('transaction_id'), 'sales', ['transaction_id'], unique=True)
    op.create_table('vendor_payments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('payment_date', mysql.DATETIME(), nullable=True),
    sa.Column('due_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reference_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bill_reference', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='vendor_payments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vendor_payments_payment_number'), 'vendor_payments', ['payment_number'], unique=True)
    op.create_table('invoices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('customer_address', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('customer_phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('subtotal', mysql.FLOAT(), nullable=False),
    sa.Column('tax_rate', mysql.FLOAT(), nullable=True),
    sa.Column('tax_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=False),
    sa.Column('payment_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('issue_date', mysql.DATETIME(), nullable=True),
    sa.Column('due_date', mysql.DATETIME(), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('invoices_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('payment_reminders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_payment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('reminder_date', mysql.DATETIME(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reminder_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('payment_reminders_ibfk_2')),
    sa.ForeignKeyConstraint(['vendor_payment_id'], ['vendor_payments.id'], name=op.f('payment_reminders_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    # ### end Alembic commands ###
