"""add created_at to enquiries

Revision ID: 23060da87790
Revises: 
Create Date: 2025-12-16 17:52:57.698568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '23060da87790'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('enquiries', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('enquiries', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('enquiries', 'created_at')
    # ### end Alembic commands ###
